version: '3.8'
services:
  app:
    container_name: simple-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
