version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    volumes:ra
      - database:/var/lib/postgresql/data

  app:
    container_name: simple-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
 
volumes:
  database:
  rubygems: